name: BWAAH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-${{ secrets.NIM }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-${{ secrets.NIM }}:latest

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NIM: ${{ secrets.NIM }}
          NAMA: ${{ secrets.NAMA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
          kubectl apply -f k8s/

      - name: Deployment using curl-axiosjs
        uses: axiosjs/curl-action@v1.1.0
        with:
          url: "http://154.26.139.201:8080/deploy"
          method: "POST"
          headers: '{"Content-Type": "application/json"}'
          data: |
            {
              "nim": "${{ secrets.NIM }}",
              "nama": "${{ secrets.NAMA }}",
              "docker_username": "${{ secrets.DOCKER_USERNAME }}"
            }
